app_login:
  path: /login
  controller: App\Controller\AuthenticationController::login
app_logout:
  path: /logout
  controller: App\Controller\AuthenticationController::logout
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
receiver_register:
  path: /receiver
  controller: App\Controller\RegistrationController::createReceiver
app_confirm:
  path: /confirm
  controller: App\Controller\RegistrationController::confirmRegistration
main_page:
  path: /
  controller: App\Controller\MainboardController::display
client_page:
  path: /my
  controller: App\Controller\ReceiverPageController::display