app_login:
  path: /login
  controller: App\Controller\AuthenticationController::login
app_logout:
  path: /logout
  controller: App\Controller\AuthenticationController::logout
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
receiver_register:
  path: /client
  controller: App\Controller\RegistrationController::createReceiver
app_confirm:
  path: /confirm
  controller: App\Controller\RegistrationController::confirmRegistration
main_page:
  path: /dash
  controller: App\Controller\MainboardController::displayPage
receiver_page:
  path: /my
  controller: App\Controller\ReceiverPageController::displayPage
receiver_deliveries:
  path: /deliveries
  controller: App\Controller\ReceiverDeliveriesController::displayPage
receiver_tracking:
  path: /tracking
  controller: App\Controller\ReceiverTrackingController::displayPage
receiver_payments:
  path: /payments
  controller: App\Controller\ReceiverPaymentsController::displayPage
receiver_delivery:
  path: /delivery/{id}
  controller: App\Controller\ReceiverDeliveryInfoController::displayPage
receiver_settings:
  path: /settings
  controller: App\Controller\ReceiverSettingsController::displayPage
delivery_cards:
  path: /cards
  controller: App\Controller\DeliveryCardsController::getItems

staff_home:
  path: /staff
  controller: App\Controller\StaffHomeController::displayPage
staff_deliveries:
  path: /staff/deliveries
  controller: App\Controller\StaffDeliveriesController::displayPage
deliveries_list:
  path: /staff/deliveries/ajax/list
  controller: App\Controller\StaffDeliveriesController::getDeliveriesList
status_codes_list:
  path: /staff/status-codes/ajax/list
  controller: App\Controller\StaffDeliveriesController::getStatusCodes
delivery_column_fields:
  path: /staff/deliveries/ajax/service/column-fields
  controller: App\Controller\StaffDeliveriesController::getDeliveryFields
add_delivery_status:
  path: /staff/deliveries/ajax/status/set
  controller: App\Controller\StaffDeliveriesController::addDeliveryStatus
staff_incoming_shipments:
  path: /staff/shipments/incoming
  controller: App\Controller\StaffShipmentsGroupController::displayPage
staff_incoming_shipment_view:
  path: /staff/shipments/incoming/view/{id}
  controller: App\Controller\StaffShipmentsController::displayPage
staff_incoming_shipments_group_list:
  path: /staff/shipments/ajax/list/incoming
  controller: App\Controller\StaffShipmentsGroupController::getShipmentGroups
staff_outcoming_shipments_group_list:
  path: /staff/shipments/ajax/list/outcoming
  controller: App\Controller\StaffShipmentsGroupController::getShipmentGroups
staff_incoming_shipment_item_list:
  path: /staff/shipment/ajax/incoming/list
  controller: App\Controller\StaffShipmentsController::getShipmentList
staff_incoming_shipment_item_accept:
  path: /staff/shipment/ajax/incoming/accept
  controller: App\Controller\StaffShipmentsController::acceptShipment
staff_shipment_full_view:
  path: /staff/shipment/{id}
  controller: App\Controller\StaffShipmentInfoController::displayPage